version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    commit-message:
      prefix: "ci:"
    labels: ["actions"]
    # only needed for non-default branch
    #target-branch: "develop"
    groups:
      all-actions:
        patterns: [ "*" ]

  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "pcr"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci:"
    labels: ["dependencies"]
    allow:
      - dependency-name: "all"
    groups:
      python-packages:
        patterns: [ "*" ]
